const Constants = {
    SHELTERS_FETCHING: 'SHELTERS_FETCHING',
    SHELTERS_RECEIVED: 'SHELTERS_RECEIVED',
    SHELTER_FETCHING: 'SHELTER_FETCHING',
    SHELTER_RECEIVED: 'SHELTER_RECEIVED',
};

export default Constants;
